{% set version = "0.1.48" %}

package:
  name: typos-lsp
  version: {{ version }}

source:
  url: https://github.com/tekumara/typos-lsp/archive/v{{ version }}.tar.gz
  sha256: cecf41f1f0967edb7d4c1ffebdbef9165c710a8fd7117c0f0488f33e8406aa32

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - typos-lsp &  # [unix]
    - exe_pid=$!  # [unix]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [unix]
    - start /b typos-lsp   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im typos-lsp.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/tekumara/typos-lsp
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Source code spell checker for Visual Studio Code, Neovim and other LSP clients
  dev_url: https://github.com/tekumara/typos-lsp

extra:
  recipe-maintainers:
    - danielnachun
